//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : AND.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_AND_H)
#define _AND_H

#include "DigitalGate.h"

class AND: public DigitalGate
{
public:

	AND();

	void acceptVisitor(Visitor*);		// visitor

protected:

	void process();			// redefinition

};

#endif  //_AND_H