//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : NOR.cpp
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//

#include "NOR.h"

void NOR::process()
{
	if (getInPinVal(0) == 1 || getInPinVal(1) == 1)
		setOutPinValDemo(0);
	else
		setOutPinValDemo(1);
}

NOR::NOR() :
		DigitalGate(0.012, 0.008)
{

}

void NOR::acceptVisitor(Visitor* v)
{
	v->visitNorGate(this);
}
