//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : NOR.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_NOR_H)
#define _NOR_H

#include "DigitalGate.h"

class NOR: public DigitalGate
{
public:

	NOR();

	void acceptVisitor(Visitor*);		// visitor

protected:

	void process();			// redefiniton

};

#endif  //_NOR_H