//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : NOT.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_NOT_H)
#define _NOT_H

#include "DigitalGate.h"

class NOT: public DigitalGate
{
public:

	NOT();

protected:

	void process();		// redefiniton

	void acceptVisitor(Visitor*);		// visitor

	void readInputPins();		// redefiniton

	bool inputsShortened();		// redefiniton

};

#endif  //_NOT_H