//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : OR.cpp
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//

#include "OR.h"

void OR::process()
{
	if (getInPinVal(0) == 1 || getInPinVal(1) == 1)
		setOutPinValDemo(1);
	else
		setOutPinValDemo(0);
}

OR::OR() :
		DigitalGate(0.010, 0.014)
{

}

void OR::acceptVisitor(Visitor* v)
{
	v->visitOrGate(this);
}
