//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : OR.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_OR_H)
#define _OR_H

#include "DigitalGate.h"

//predstavlja ILI kolo
class OR: public DigitalGate
{
public:

	OR();

	void acceptVisitor(Visitor*);		// visitor

protected:

	void process();			// redefiniton

};

#endif  //_OR_H