//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : DigitalProbe.h
//  @ Date : 8.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_DIGITALPROBE_H)
#define _DIGITALPROBE_H

#include "../model/ModelElement.h"
#include "../gates/DigitalGate.h"
#include "../model/SignalChange.h"
#include <vector>

using namespace std;

// probe
class DigitalProbe : public ModelElement
{
public:

	DigitalProbe();
	virtual ~DigitalProbe();

	void acceptSignal();		// redefiniton		
	void notify(Description);		// redefiniton. no function
	void acceptVisitor(Visitor*);		// visitor


	void setSource(ModelElement*);			// redefiniton
	void setTarget(ModelElement*);			// redefiniton. no function

	SignalValue getOutPinVal();			// redefiniton. no function

	Time getDelay0to1();			// redefiniton
	Time getDelay1to0();			// redefiniton

	vector<SignalChange> getChanges();

	ModelElement* source;		// source for probe

protected:

	void process();		// helper. Records signal changes

	void addChange(SignalChange);
	
private:	

	vector<SignalChange> changes;

	SignalValue lastVal;
	SignalValue curVal;

	// delays
	Time delay0to1;
	Time delay1to0;		

};


#endif  //_DIGITALPROBE_H
