//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ConnectionDescription.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_CONNECTIONDESCRIPTION_H)
#define _CONNECTIONDESCRIPTION_H

#include "typedefs.h"

// store connection description of circuit from file in specific format. Stores IDx-pinx connected to IDy-piny
class ConnectionDescription
{
public:
	
	ConnectionDescription(ID i1, unsigned int pin1, ID i2, unsigned int pin2):
		idX(i1),
		idY(i2),
		pinX(pin1),
		pinY(pin2)
	{

	}

	ID idX;
	ID idY;

	unsigned int pinX ;
	unsigned int pinY;

};

#endif  //_CONNECTIONDESCRIPTION_H
