//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Reader.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_READER_H)
#define _READER_H

#include "Data.h"
#include "../helpers/CLKSource.h"
#include "../helpers/ASource.h"
#include "../helpers/ISource.h"
#include "typedefs.h"

#include <iostream>
#include <fstream>
#include <string>


using namespace std;

// reads data from circuit description file and puts it into object of class Data
class Reader
{
public:

	static Reader* Instance ();		// singleton

	~Reader();

	void readData(char*, char*);		// fills Data object
	Data* getData();

protected:

	Reader();

	void parseInputFile(char*);		// helper for file parsing

	void sourceInitialize(unsigned int, string);		// helper, creates dummy elements? TODO: examine
	
private:
			
	Data* data;			// data object

};

#endif  //_READER_H
