//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : CLKSource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_CLKSOURCE_H)
#define _CLKSOURCE_H

#include "Source.h"
#include "../model/Model.h"
#include "../sources/ClockSource.h"
#include "../model/Reader.h"

// dummy clock source
class CLKSource : public Source
{
public:

	CLKSource();
	~CLKSource();

	void setFrequency(Frequency);
	Frequency getFrequency();

	void createConcreteElement();		// redefinition
	
private:

	Frequency frequency ;
};

#endif  //_CLKSOURCE_H
