//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Element.cpp
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//

#include "Element.h"

Element::Element() :
		type(0), id(0)
{

}

Element::Element(Type t, ID i)
{
	type = t;
	id = i;
}

ID Element::getId()
{
	return id;
}

Type Element::getType()
{
	return type;
}

void Element::setID(ID i)
{
	id = i;
}

Element::~Element()
{

}
