//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ISource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_ISOURCE_H)
#define _ISOURCE_H

#include "Source.h"
#include "../model/Model.h"
#include "../sources/ImpulsSource.h"
#include "../model/Reader.h"

// dummy impuls source
class ISource : public Source
{
public:

	ISource();
	~ISource();

	void setImpulsLevel(SignalValue lev);		
	SignalValue getImpulsLevel();

	void setFrequency(Frequency f);
	Frequency getFrequency();

	void setImpulsTime(Time iTime);
	Time getImpulsTime();

	void createConcreteElement();			// redefiniton

private:

	Frequency frequency;			// freq
	SignalValue impulsLevel;		// activ impuls level
	Time impulsActiveTime;			// impuls duration

};

#endif  //_ISOURCE_H
