//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Probe.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_PROBE_H)
#define _PROBE_H

#include "Element.h"

// dummy probe
class Probe: public Element
{
public:

	Probe();
	Probe(ID, Type);
	~Probe();

	void createConcreteElement();			// redefiniton

};

#endif  //_PROBE_H