//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Source.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_SOURCE_H)
#define _SOURCE_H

#include "Element.h"

// dummy source
class Source: public Element
{
public:

	Source();
	Source(ID, Type);
	~Source();

	virtual void createConcreteElement();		// redefinition

};

#endif  //_SOURCE_H