//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Source.cpp
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#include "Source.h"

Source::Source()
:	Element()
{


}

Source::Source(ID i,Type t)
:	Element(t,i)
{


}

Source::~Source()
{
	
}

void Source::createConcreteElement()
{

}
