//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ASource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_ASOURCE_H)
#define _ASOURCE_H
#define ASOURCE_MAXNUMOFCHANGES 50

#include "Source.h"
#include "../sources/ArbitrarySource.h"
#include "../model/Model.h"
#include "../model/Reader.h"

// dummy class for source with manual configuration
class ASource : public Source
{
public:

	ASource();
	~ASource();

	// initial signal value
	void setInitialVal(SignalValue iVal);		
	SignalValue getInitialVal();

	// time of signal change
	void setMomOfChange(Time moment);		
	Time* getMomsOfChange();

	unsigned int getNumOfChanges();	

	void createConcreteElement();		// redefinition

private:

	SignalValue initialValue;		// initial value of source signal

	Time momentsOfChange[ASOURCE_MAXNUMOFCHANGES];		// moments of signal change
	unsigned int numberOfChanges;			// number of changes

};

#endif  //_ASOURCE_H
