//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital circuit analyzer
//  @ File Name : Event.h
//  @ Date : 20.4.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_EVENT_H)
#define _EVENT_H
#include "../model/typedefs.h"
#include "../model/ModelElement.h"
#include "Scheduler.h"

//klasa koja modelira dogadjaj u sistemu. Dogadjaji ce biti ulancani u formi liste u zavisnosti kada su se pojavljivali
class Event
{
public:

	static void create(ModelElement*, Time, ID, Description);
	//dogadjaj se stvara na osnovu elementa koji ga je proizveo, vremena kada se pojavio	
	//ID-ja elementa koji ga je izazvao i deskripcije(opisa dogadjaja)

	ModelElement* getTarget();
	Time getTime();
	void setTime(Time);
	ID getID();
	void setID(ID);
	Description getDescription();
	Event* getNext();
	void setNext(Event*);

private:

	Event(ModelElement*, Time, ID, Description);

	ModelElement* target;
	Time time;
	ID id;
	Description descr;

	Event* next;//sledeci u nizu dogadjaja. Lista dogadjaja se formira u Scheduler-u
};

#endif  //_EVENT_H