//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit  Analyzer
//  @ File Name : StatDescr.h
//  @ Date : 28.5.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_STATDESCR_H)
#define _STATDESCR_H

#include <string>
#include "../model/typedefs.h"

const ID MAXNUMOFTARGETIDS = 50;
const ID MAXNUMOFSOURCEIDS = 2;

using namespace std;

// helper class for statistics. Statistics is ment to be written at sim end
class StatDescr
{
public:
		
	StatDescr(string, string , string, ID, ID[], ID[], unsigned int, unsigned int);

	// strings and IDs to appear in statistics
	string descrMain;
	ID idMain;

	string descr2;
	ID targets[MAXNUMOFTARGETIDS];

	string descr3;
	ID sources[MAXNUMOFSOURCEIDS];

	unsigned int getNumT();
	unsigned int getNumS();

private:
	// num targets, num sources
	unsigned int numT;
	unsigned int numS;

};

#endif  //_STATDESCR_H
