//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit  Analyzer
//  @ File Name : Visitor.h
//  @ Date : 21.4.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_VISITOR_H)
#define _VISITOR_H

class Model;
class DigitalProbe;
class AND;
class OR;
class NAND;
class NOR;
class NOT;
class ArbitrarySource;
class ImpulsSource;
class ClockSource;

// visitor
class Visitor
{
public:

	void visitModel(Model*);	// final

	// visiting elements. To be redefined
	virtual void visitDigitalProbe(DigitalProbe*);
	virtual void visitAndGate(AND*);
	virtual void visitNandGate(NAND*);
	virtual void visitOrGate(OR*);
	virtual void visitNorGate(NOR*);
	virtual void visitNotGate(NOT*);
	virtual void visitASource(ArbitrarySource*);
	virtual void visitClkSource(ClockSource*);
	virtual void visitISource(ImpulsSource*);
	virtual ~Visitor();

};

#endif  //_VISITOR_H