//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit  Analyzer
//  @ File Name : Visitor.cpp
//  @ Date : 21.4.2013
//  @ Author : Lazar Kovacevic
//
//


#include "../model/Model.h"
#include "Visitor.h"


void Visitor::visitModel (Model* m)
{  
	for (unsigned int i=0; i < m->getElements().size(); i++)
		m->getElements()[i]->acceptVisitor(this);  

}
void Visitor::visitDigitalProbe(DigitalProbe* dp)
{

}

void Visitor::visitAndGate(AND* gate)
{

}

void Visitor::visitNandGate(NAND* gate)
{

}

void Visitor::visitOrGate(OR* gate)
{

}

void Visitor::visitNorGate(NOR* gate)
{

}

void Visitor::visitNotGate(NOT* gate)
{

}

void Visitor::visitASource(ArbitrarySource* source)
{

}

void Visitor::visitISource(ImpulsSource* source)
{

}

void Visitor::visitClkSource(ClockSource* source)
{

}

Visitor::~Visitor()
{

}
