//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit  Analyzer
//  @ File Name : visStatistics.h
//  @ Date : 28.5.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_VISSTATISTICS_H)
#define _VISSTATISTICS_H

#include "Visitor.h"
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include "../model/Reader.h"
#include <iomanip>
#include "../model/typedefs.h"

#include "../probes/DigitalProbe.h"
#include "StatDescr.h"
#include "../gates/AND.h"
#include "../gates/NAND.h"
#include "../gates/NOR.h"
#include "../gates/OR.h"
#include "../gates/NOT.h"

// visitor for statistics report
class visStatistics: public Visitor
{

public:

	visStatistics();

	// redefine
	void visitDigitalProbe(DigitalProbe*);
	void visitAndGate(AND*);
	void visitNandGate(NAND*);
	void visitOrGate(OR*);
	void visitNorGate(NOR*);
	void visitNotGate(NOT*);
	void visitASource(ArbitrarySource*);
	void visitClkSource(ClockSource*);
	void visitISource(ImpulsSource*);
	void writeStats();			// write statistics

	vector<StatDescr> descriptions;			// stats to be writen

private:

	// TODO:???
	unsigned int ANDnum;
	unsigned int NANDnum;
	unsigned int NORnum;
	unsigned int ORnum;
	unsigned int NOTnum;
	unsigned int ASourceNum;
	unsigned int ClkSourceNum;
	unsigned int ISourceNum;
	unsigned int probeNum;

};

#endif  //_VISSTATISTICS_H