//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit  Analyzer
//  @ File Name : VisSimReporter.h
//  @ Date : 21.4.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_VISSIMREPORTER_H)
#define _VISSIMREPORTER_H

#include "Visitor.h"
#include <iostream>
#include <sstream>
#include <fstream>
#include "../model/Reader.h"
#include "../probes/DigitalProbe.h"
#include <iomanip>

// Visitor for simulation results report
class VisSimReporter: public Visitor
{
public:

	void visitDigitalProbe(DigitalProbe*);		// redefinition	

protected:

	void writeChanges(ostream&, DigitalProbe*);	// write changes in specific format

};

#endif  //_VISSIMREPORTER_H