//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : DigitalSource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_DIGITALSOURCE_H)
#define _DIGITALSOURCE_H
#define SOURCE_MAXNUMOFTARGETS 100

#include "../model/ModelElement.h"
#include "../gates/DigitalGate.h"

// digital source abstraction
class DigitalSource : public ModelElement
{
public:

	virtual ~DigitalSource();

	virtual void acceptSignal();			// redefiniton. no function since source creates signals
	
	void setTarget(ModelElement* t);		// redefiniton
	void setSource(ModelElement* t);		// redefiniton. no function since source has no input pins

	Time getDelay0to1();			// redefiniton
	Time getDelay1to0();			// redefiniton
	

	void changeOutPinVal();			// toggle out pin value
	SignalValue getOutPinVal();		// redefiniton

	unsigned int getNumOfTargets();

	ModelElement* target[SOURCE_MAXNUMOFTARGETS];

		
protected:

	DigitalSource();
	// helper method to notify. Changes signal and puts it onto targets
	virtual void process();	

	// helper method. Creates first event when source is created and puts it into sched. To be redefined. TODO: is this really needed?
	virtual void turnOn()=0;
	
private:	

	unsigned int numberOfTargets;
	SignalValue outPinVal;
	Time delay0to1;
	Time delay1to0;
};

#endif  //_DIGITALSOURCE_H
