//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ArbitrarySource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_ARBITRARYSOURCE_H)
#define _ARBITRARYSOURCE_H

#define ASOURCE_MAXNUMOFCHANGES 50

#include "DigitalSource.h"
#include "Event.h"
#include "Model.h"
#include "Reader.h"

//Ova klasa reprezentuje izvor sa rucnim podesavanjem.
class ArbitrarySource : public DigitalSource
{
public:

	ArbitrarySource(ID, SignalValue, Time*, unsigned int);			//konstruktor
	~ArbitrarySource();

	void notify(Description);		//redefinicija
	void acceptVisitor(Visitor*);	//visitor 

	SignalValue getInitialValue();		//dohvatanje pocetne vrednosti izvora

	Time getMomOfChange(unsigned int);		//dohvatanje momenta promene signala na izlazu izvora
	unsigned int getNumOfChanges();			//dohvatanje broja promena signala na izlazu izvora

protected:

	void turnOn();		//redefinicija

private:

	SignalValue initialValue;			//pocetna vrednost izvora

	Time momentsOfChange[ASOURCE_MAXNUMOFCHANGES];		//momenti kada izvor menja vrednost izlaznog signala
	unsigned int numberOfChanges;			//broj promena signala

	unsigned int counter;			//brojac promena vrednosti izl. signala izvora, pomocno polje
};

#endif  //_ARBITRARYSOURCE_H
