//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ASource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_ASOURCE_H)
#define _ASOURCE_H
#define ASOURCE_MAXNUMOFCHANGES 50

#include "Source.h"
#include "ArbitrarySource.h"
#include "Model.h"

//'dummy' klasa, predstvalja izvor sa rucnim podesavanjem
class ASource : public Source
{
public:

	ASource();
	~ASource();

	void setInitialVal(SignalValue iVal);		//postavljanje poc. vredn. signala
	SignalValue getInitialVal();			//dohvatanje poc. vredn. signala

	void setMomOfChange(Time moment);		//postavljanje momenata kada se signal menja
	Time* getMomsOfChange();			//dohvatanje momenata kada se signal menja

	unsigned int getNumOfChanges();			//dohvatanje broja promena signala

	void spawnThisElmenet();		//redefinicija

private:

	SignalValue initialValue;		//pocetna vrednost arb. izvora

	Time momentsOfChange[ASOURCE_MAXNUMOFCHANGES];		//momenti promena signala
	unsigned int numberOfChanges;			//broj promena signala

};

#endif  //_ASOURCE_H
