//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Builder.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_BUILDER_H)
#define _BUILDER_H

#include "Data.h"
#include "Model.h"

//graditelj modela, singleton
//na osnovu objekta klase Data izgradjuje model i povezuje ga
class Builder
{
public:

	~Builder();

	void buildModel(Data* data);	//metoda koja na osnovu podataka sacuvanih objektu klase Data izgradjuje model sistema

	static Builder* Instance();		//klasa Builder je singleton

protected:

	Builder()
	{

	}

	void link(ID, unsigned int, ID, unsigned int );		//pomocna metoda metode buildModel, koja povezuje elemente kola na osnovu njihovih ID-jeva i pinova

};

#endif  //_BUILDER_H
