//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : CLKSource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_CLKSOURCE_H)
#define _CLKSOURCE_H

#include "Source.h"
#include "Model.h"
#include "ClockSource.h"

//'dummy' klasa, predstavlja izvor signala takta
class CLKSource : public Source
{
public:

	CLKSource();
	~CLKSource();

	void setFrequency(Frequency);			//postavljanje i dohvatanje frekvencije
	Frequency getFrequency();

	void spawnThisElmenet();		//redefinicija
	
private:

	Frequency frequency ;		//frekvencija izvora signala takta
};

#endif  //_CLKSOURCE_H
