//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ClockSource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_CLOCKSOURCE_H)
#define _CLOCKSOURCE_H

#include "DigitalSource.h"
#include "Event.h"
#include "Model.h"
#include "Reader.h"

//Ova klasa reprezentuje izvor signala takta
class ClockSource : public DigitalSource
{
public:

	ClockSource(ID, Frequency);			//konstruktor
	~ClockSource();

	void notify(Description);			//redefinicija	
	void acceptVisitor(Visitor*);		//visitor

	Frequency getFrequency();		//dohvatanje frekvencije
	
protected:

	void turnOn();			//redefinicija
	
private:

	Frequency frequency;		//frekvencija izvora taktnog signala
};

#endif  //_CLOCKSOURCE_H
