//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Data.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_DATA_H)
#define _DATA_H
#define MAXNUMOFELEMENTS 100

#include "Element.h"
#include "Probe.h"
#include "Gate.h"
#include "Source.h"
#include "ConnectionDescription.h"
#include <string>
#include <vector>

using namespace std;

//svrha ove klase je da cuva znacajne podatke procitane iz ulaznog fajla i klasifikuje ih
//sadrzi listu 'dummy' elemenata na osnovu kojih ce kasnije(polimorfno) biti generisani pravi elementi modela (prolaskom kroz listu 'dummy' elemenata
//i pozivanjem metode spawnThisElement)
class Data
{
public:

	Data();
	~Data();

	vector<Element*> getElements();			//dohvatanje liste sa 'dummy' elementima
	vector<ConnectionDescription*> getConnDescr();			//dohvatanje liste sa opisima veza izmedju elemenata elementima
	void addConnDescr(ConnectionDescription*);			//dodavanje opisa veze izmedju elemenata
	void addElement(Element* e);			//dodavanje dummy 'elementa' u listu 'dummy' elemenata
	void deleteElement(unsigned int i);			//brisanje elementa iz liste 'dummy' elemenata na odgovarajucoj poziciji

	unsigned int getNumberOfElements();				//dohvatanje i postavljanje broja elemenata
	void setNumberOfElements(unsigned int num);
	
	void setSimTime(Time t);			//vreme trajanja simulacije postavljanje i dohvatanje
	Time getSimTime();

	void setTOFE(Time);				//postavljanje i dohvatanje vremena prvog dogadjaja u kolu
	Time getTOFE();	

	string getFileName();		//dohvatanje imena fajla iz koga se citaju specifikacije kola
	void setFileName(char*);

	string getOutPath();		//dohvatanje imena fajla u koji se upisuju rez. simulacije
	void setOutPath(char*);		
	
		
private:

	vector<Element*> elements;		//skup 'dummy' elemenata koji ce biti kreirani kako se prolazi kroz ulazni fajl
									//svrha 'dummy' elemenata je da opise stvarne elemente koji ce kasnije biti kreirani na osnovu demo elemenata.
									//svaki 'dummy' element ima polimorfnu metodu spawnThisElement() koja stvara pravi fizicki element.

	vector<ConnectionDescription*> connDescr;		//skup opisa veza izmedju elemenata

	Time simulationTime;		//ukupno vreme simulacije

	unsigned int numberOfElements;			//broj elemenata kola
	
	Time timeOfFirstEvent;		//vreme prvog dogadjaju u kolu koji niji izazvan inicijalizacijom kola (TOFE)

	string name;		//argv[1]- ime fajla iz koga se citaju podaci
	string outPath;		//argv[2]- ime fajla gde se cuvaju rezultati simulacije
};

#endif  //_DATA_H
