//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : DigitalSource.cpp
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#include "DigitalSource.h"

DigitalSource::~DigitalSource()
{

}

void DigitalSource::process()
{
	changeOutPinVal();
	for(unsigned int i=0; i<getNumOfTargets();i++)
		target[i]->acceptSignal();
}

DigitalSource::DigitalSource():
	ModelElement(),
 	numberOfTargets(0),
 	outPinVal(0),
 	delay0to1(0),
 	delay1to0(0)
{

}

Time DigitalSource::getDelay0to1()
{
	return delay0to1;
}

Time DigitalSource::getDelay1to0()
{
	return delay1to0;

}

void DigitalSource::acceptSignal()
{

}

unsigned int DigitalSource::getNumOfTargets()
{
	return numberOfTargets;
}

void DigitalSource::setTarget(ModelElement* t)
{
	target[numberOfTargets]=t;
	numberOfTargets++;
}

void DigitalSource::setSource(ModelElement* t)
{

}

void DigitalSource::changeOutPinVal()
{
	if(outPinVal==1)
		outPinVal=0;
	else
		outPinVal=1;
}

SignalValue DigitalSource::getOutPinVal()
{
	return outPinVal;
}
