//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : DigitalProbe.h
//  @ Date : 8.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_DIGITALPROBE_H)
#define _DIGITALPROBE_H

#include "ModelElement.h"
#include "DigitalGate.h"
#include "SignalChange.h"
#include "Reader.h"
#include <vector>

using namespace std;

//predstavlja sondu
//U sondi se beleze sve promene signala, pa ce se na kraju simulacije iz sonde i procitati te promene (upotrebom visitor obrasca)
class DigitalProbe : public ModelElement
{
public:

	DigitalProbe();
	virtual ~DigitalProbe();

	void acceptSignal();		//redefinicija		
	void notify(Description);		//redefinicija. Ne radi nista
	void acceptVisitor(Visitor*);		//visitor


	void setSource(ModelElement*);			//redefinicija
	void setTarget(ModelElement*);			//redefinicija. Ne radi nista. Sonda nema izlazne pinove pa nema ni mete

	SignalValue getOutPinVal();			//redefinicija. Ne radi nista. Sonda nema izlazni signal

	Time getDelay0to1();			//redefinicija
	Time getDelay1to0();			//redefinicija

	vector<SignalChange> getChanges();			//dohvatanje liste promena signala sonde

	ModelElement* source;		//izvor signala za sondu

protected:

	void process();		//pomocna metoda. Snimanje promene vrednosti signala na sondi

	void addChange(SignalChange);		//dodavanje promene u listu sa promenama
	
private:	

	vector<SignalChange> changes;		//lista sa promenama signala

	SignalValue lastVal;		//poslednja vrednost izmerena na sondi
	SignalValue curVal;			//vrednost trenutno izmerena na sondi
	Time delay0to1;				//kasnjenja
	Time delay1to0;		

};


#endif  //_DIGITALPROBE_H
