//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Element.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_ELEMENT_H)
#define _ELEMENT_H

#include "TYPEDEFINITIONS.h"

//'dummy' klasa. Predstavlja element koji sluzi samo za lakse kasnije generisanje pravog elementa koji ce se koristiti u modelu
//sve moguce vrste elemenata('dummy' elemenata) koje se mogu pojaviti u sistemu bice izvedene iz ove klase - gate, source...
//Apstraktna klasa
class Element
{
public:

	virtual ~Element();			

	ID getId();				//dohvatanje ID-ja
	void setID(ID);			//postavljanje ID-ja

	Type getType();				//dohvatanje tipa elementa

	virtual void spawnThisElmenet()=0;		//na osnovu tipa (tekuceg) elementa stvara realni element koji ce se koristiti u modelu.
											//bice redefinisano u izv. klasama	
											//ideja je da se iz liste razlicitih 'dummy' elemenata
protected:

	Element(Type, ID);			//stvaranje dummy elementa na osnovu ID-ja i tipa, konstruktor

	Element();

private:

	Type type;		//tip elementa (5 - izvor ... iz specifikacija)

	ID id;			//ID
};

#endif  //_ELEMENT_H
