//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Gate.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_GATE_H)
#define _GATE_H


#include "Element.h"

//'dummy' klasa, predstavlja gejt
class Gate : public Element
{
public:

	Gate();
	Gate(ID, Type);		
	~Gate();

	void spawnThisElmenet();		//redefinicija

};

#endif  //_GATE_H
