//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ImpulsSource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_IMPULSSOURCE_H)
#define _IMPULSSOURCE_H

#include "DigitalSource.h"
#include "Event.h"
#include "Model.h"
#include "Reader.h"

//ova klasa reprezentuje impulsni izvor
class ImpulsSource : public DigitalSource
{
public:

	ImpulsSource(ID, Frequency, SignalValue, Time);
	~ImpulsSource();

	void notify(Description);		//redefinicija
	void acceptVisitor(Visitor*);	//visitor


	SignalValue getImpulsLeve();		//dohvatanje pojedinih atributa...
	Frequency getFrequency();
	Time getImpulsTime();

protected:

	void turnOn();					//redefinicija

private:

	SignalValue impulsLevel;		//aktivan logicki nivo impulsa
	Frequency frequency;			//frekvencija izvora
	Time impulsActiveTime;			//vreme trajanja impulsa

	bool flag;			//pomocni flag

};

#endif  //_IMPULSSOURCE_H
