//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ISource.cpp
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#include "ISource.h"

ISource::~ISource()
{

}

void ISource::spawnThisElmenet()
{
	ImpulsSource* s = new ImpulsSource(Element::getId(), frequency, impulsLevel, impulsActiveTime);
}

ISource::ISource():
		Source(),
		frequency(1000),
		impulsLevel(0),
		impulsActiveTime(0)
		{

		}
void ISource::setImpulsLevel(SignalValue lev)
{
	impulsLevel=lev;
}

SignalValue ISource::getImpulsLevel()
{
	return impulsLevel;
}

void ISource::setFrequency(Frequency f)
{
	frequency=f;
}

Frequency ISource::getFrequency()
{
	return frequency;
}

void ISource::setImpulsTime(Time iTime)
{
	impulsActiveTime=iTime;
}

Time ISource::getImpulsTime()
{
	return impulsActiveTime;
}
