//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ISource.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_ISOURCE_H)
#define _ISOURCE_H

#include "Source.h"
#include "Model.h"
#include "ImpulsSource.h"

//'dummy' klasa, predstavlja impulsni izvor
class ISource : public Source
{
public:

	ISource();
	~ISource();

	//postavljanje i dohvatanje pojedinih atributa klase
	void setImpulsLevel(SignalValue lev);		
	SignalValue getImpulsLevel();

	void setFrequency(Frequency f);
	Frequency getFrequency();

	void setImpulsTime(Time iTime);
	Time getImpulsTime();

	void spawnThisElmenet();			//redefinicja

private:

	Frequency frequency;			//frekvencija
	SignalValue impulsLevel;		//aktivan nivo impulsa
	Time impulsActiveTime;			//vreme trajanja impulsa

};

#endif  //_ISOURCE_H
