//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : ModelElement.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_MODELELEMENT_H)
#define _MODELELEMENT_H

#include "TYPEDEFINITIONS.h"
#include "Visitor.h"

//predstavlja najopstiju sliku elementa modela. Apstraktna klasa
//iz ove klase bice izvedeni svi specificni elementi - gejtovi, izvori, sonde...
class ModelElement
{
public:

	virtual ~ModelElement();

	virtual void acceptVisitor(Visitor*) = 0;		//visitor
	virtual void acceptSignal() =0;		//metoda koja se poziva kada element prima signal
										

	virtual void notify(Description) = 0;		//metoda koju pokrece Scheduler kada dogadjaj koji je pokrenulo ovo kolo stigne na red za izvrsavanje
												

	virtual void setTarget(ModelElement*) =0;		//metoda za postavljanje meta ovog elementa
	virtual void setSource(ModelElement*) =0;		//metoda za postavljanje izvora za ovaj element

	virtual SignalValue getOutPinVal() =0;			//ocitavanje vrednosti signala na izl. pinu/pinovima

	virtual Time getDelay0to1() =0;					//dohvatanje kasnjenja elementa
	virtual Time getDelay1to0() =0;

	void setId(ID Id);					//postavljanje i uzimanje ID-ja elementa
	ID getId();

protected:

	ModelElement();

private:

	ID id;			//ID elementa

};

#endif  //_MODELELEMENT_H
