//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Model.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_MODEL_H)
#define _MODEL_H

#include <vector>
#include "ModelElement.h"
#include "Visitor.h"

using namespace std;

//predstavlja celokupan model sa svim elementima. Singlton
class Model
{
public:

	~Model();

	static Model* Instance();		//singleton

	void acceptVisitor(Visitor*);		//visitor

	void add(ModelElement*);		//dodavanje elementa u model
	vector<ModelElement*> getElements();		//dohvatanje svih elemenata modela

	void clearModel();		//brisanje svih elemenata modela

	ModelElement* findElement(ID);			//pronalazak elementa na osnovu njegovog ID-ja

protected:

	Model();

private:

	vector<ModelElement*> elements;		//svi elementi modela
};

#endif  //_MODEL_H
