//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Model.cpp
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#include "Model.h"

Model::Model()
{

}

void Model::acceptVisitor(Visitor* v)
{
	if(v)
		v->visitModel(this);
}

void Model::add(ModelElement* me)
{
	elements.push_back(me);
}

vector <ModelElement*> Model::getElements()
{
	return elements;
}

Model::~Model()
{
	clearModel();	
}

Model* Model::Instance()
{
	static Model instance;
	return &instance;
}

void Model::clearModel()
{
	for(unsigned int i=0; i<elements.size();i++)
		delete elements[i];	
}

ModelElement* Model::findElement(ID id)
{
	for(unsigned int i=0; i<elements.size(); i++)
		if(elements[i]->getId()==id)
			return elements[i];
	return 0;
}

