//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : NAND.cpp
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#include "NAND.h"

void NAND::process()
{
	if(getInPinVal(0)==0 || getInPinVal(1)==0)
		setOutPinValDemo(1);
	else
		setOutPinValDemo(0);
}

NAND::NAND()
:	DigitalGate(0.011, 0.007)
{

}

void NAND::acceptVisitor(Visitor* v)
{
	v->visitNandGate(this);
}
