//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : NOT.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_NOT_H)
#define _NOT_H

#include "DigitalGate.h"

//predstavlja NE kolo
class NOT : public DigitalGate
{
public:

	NOT();
	
protected:

	void process();		//redefinicija

	void acceptVisitor(Visitor*);		//visitor

	void readInputPins();		//redefinicija

	bool inputsShortened();		//redefinicija

};

#endif  //_NOT_H
