//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : Reader.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_READER_H)
#define _READER_H

#include "Data.h"
#include "CLKSource.h"
#include "ASource.h"
#include "ISource.h"

#include <iostream>
#include <fstream>
#include <string>


using namespace std;

//Klasa odgovorna za citanje podataka iz ulazne datoteke i upisivanje podataka u objekat klase Data. Singleton
class Reader
{
public:

	static Reader* Instance ();	

	~Reader();

	void readData(char*, char*);		//metoda koja na osnovu argumenata kom. linije cita ul. fajl i popunjava podacima objekat klase Data
	Data* getData();				//dohvatanje podataka

protected:

	Reader();		//Reader je singleton

	void listing(char*);		//Ovo je pomocna metoda metode readData, u ovoj metodi se vrsi veci deo obrade ul. fajla

	void sourceInitialize(unsigned int, string);		//Ovo je pomocna metoda metode listing, sluzi za stvaranje 'dummy' izvora
	
private:
			
	Data* data;			//podaci procitani iz ul. fajla i klasifikovani

};

#endif  //_READER_H
