//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital circuit analyzer
//  @ File Name : Scheduler.h
//  @ Date : 20.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_SCHEDULER_H)
#define _SCHEDULER_H
#include "TYPEDEFINITIONS.h"
#include "Event.h"
#include <cmath>

class Event;

//predstavlja jedinstven rasporedjivac dogadjaja celokupnog sistema. Elementi sistema proizvode dogadjaje koji se salju u Scheduler
//i ulancavaju u listu prema vremenu pojavljivanja. Scheduler procesira dogadjaje i tako izaziva nove dogadjaje. Ova klasa(objekat) je odgovorna i za
//vodjenje racuna o vremenu
class Scheduler
{
public:

	static Scheduler* Instance();		//singleton

	void put(Event*);		//dodaje dogadjaj, ulancava ga u listu na pravom mestu

	Time getCurTime();		//dohvata trenutno vreme

	bool processNow();		//pokrece se procesiranje dogadjaja

protected:

	Scheduler();		

	bool processOneEvent();				//pomocna metoda. Procesiranje jednog dogadjaja
	bool checkGlitch(Event*, Event*);		//pomocna metoda. Proverava da li 2 Evetn-a cine glic signal. Provera gliceva se vrsi neposredno pre
											//ulancavanja dogadjaja. Ako dva dogadjaja predstavljaju glic, oni ce biti izbaceni iz liste

private:

	Time curTime;		//trenutno vreme

	Event* first;		//pokazivac na prvi dogadjaj koji treba da se procesira

};

#endif  //_SCHEDULER_H
