Import("env")

# list of source files
fileList=[]

fileList.append('dbg/Error.cpp')

fileList.append('gatePrototypes/Source.cpp')
fileList.append('gatePrototypes/Probe.cpp')
fileList.append('gatePrototypes/ISource.cpp')
fileList.append('gatePrototypes/Gate.cpp')
fileList.append('gatePrototypes/Element.cpp')
fileList.append('gatePrototypes/CLKSource.cpp')
fileList.append('gatePrototypes/ASource.cpp')

fileList.append('gates/AND.cpp')
fileList.append('gates/DigitalGate.cpp')
fileList.append('gates/NAND.cpp')
fileList.append('gates/NOR.cpp')
fileList.append('gates/NOT.cpp')
fileList.append('gates/OR.cpp')

fileList.append('model/Builder.cpp')
fileList.append('model/Data.cpp')
fileList.append('model/Model.cpp')
fileList.append('model/ModelElement.cpp')
fileList.append('model/Reader.cpp')

fileList.append('probes/DigitalProbe.cpp')

fileList.append('scheduler/Event.cpp')
fileList.append('scheduler/Scheduler.cpp')

fileList.append('sources/ArbitrarySource.cpp')   
fileList.append('sources/ClockSource.cpp')
fileList.append('sources/DigitalSource.cpp')
fileList.append('sources/ImpulsSource.cpp')

fileList.append('visitor/StatDescr.cpp')
fileList.append('visitor/Visitor.cpp')
fileList.append('visitor/VisSimReporter.cpp')
fileList.append('visitor/visStatistics.cpp')

fileList.append('main.cpp')

# object file targets
objects = [env.Object(x) for x in fileList]

Return('objects')