//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit Analyzer
//  @ File Name : SignalChange.h
//  @ Date : 7.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_SIGNALCHANGE_H)
#define _SIGNALCHANGE_H
#include "TYPEDEFINITIONS.h"

//prosta klasa, sluzi za elegantno evidentiranje svih promena koje se desavaju u sondi
class SignalChange
{
public:
		
	SignalChange(SignalValue prev, SignalValue next, Time t):
		prevValue(prev),
		nextValue(next),
		timeOfChange(t)
		{

		}

	SignalValue prevValue;		//preth. vrednost
	SignalValue nextValue;		//naredna vrednost 

	Time timeOfChange;		//vreme promene

};




#endif  //_SIGNALCHANGE_H
