//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit  Analyzer
//  @ File Name : visStatistics.h
//  @ Date : 28.5.2013
//  @ Author : Lazar Kovacevic
//
//

#if !defined(_VISSTATISTICS_H)
#define _VISSTATISTICS_H

#include "Visitor.h"
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include "Reader.h"
#include <iomanip>
#include "TYPEDEFINITIONS.h"

#include "DigitalProbe.h"
#include "StatDescr.h"
#include "AND.h"
#include "NAND.h"
#include "NOR.h"
#include "OR.h"
#include "NOT.h"

//posetilac koji vodi statistiku modela. Prolazi kroz listu elemenata i radi zeljenu statistiku, a onda na kraju ispisuje statistiku
class visStatistics : public Visitor
{

public:
	
	visStatistics();

	//sve su redefinicije
	void visitDigitalProbe(DigitalProbe*);
	void visitAndGate(AND*);
	void visitNandGate(NAND*);
	void visitOrGate(OR*);
	void visitNorGate(NOR*);
	void visitNotGate(NOT*);
	void visitASource(ArbitrarySource*);
	void visitClkSource(ClockSource*);
	void visitISource(ImpulsSource*);	
	void writeStats();			//ispisvanje statistike

	vector<StatDescr> descriptions;			//vektor koji sadrzi statistike za pojedina kola koje treba ispisati u datoteku

private:

	//broj pojedinih kola
	unsigned int ANDnum;
	unsigned int NANDnum;
	unsigned int NORnum;
	unsigned int ORnum;
	unsigned int NOTnum;
	unsigned int ASourceNum;
	unsigned int ClkSourceNum;
	unsigned int ISourceNum;
	unsigned int probeNum;	

};

#endif  //_VISSTATISTICS_H
