//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Digital Circuit  Analyzer
//  @ File Name : VisSimReporter.h
//  @ Date : 21.4.2013
//  @ Author : Lazar Kovacevic
//
//


#if !defined(_VISSIMREPORTER_H)
#define _VISSIMREPORTER_H

#include "Visitor.h"
#include <iostream>
#include <sstream>
#include <fstream>
#include "Reader.h"
#include "DigitalProbe.h"
#include <iomanip>

//visitor koji ispisuje rezultate simulacije na kraju simulacije
class VisSimReporter : public Visitor
{
public:
	
	void visitDigitalProbe(DigitalProbe*);		//redefinicija	

protected:

	void writeChanges(ostream&, DigitalProbe*);			//kreiranje formata za ispis u vidu string stream-a

};

#endif  //_VISSIMREPORTER_H
